# Generated by Django 2.1.5 on 2019-01-10 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('second_name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=50)),
                ('experience', models.IntegerField()),
            ],
        ),
    ]
